name: CI

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 1,16 * *'

jobs:
    tests:
        name: PHP ${{ matrix.php }}, SF ${{ matrix.symfony }} - ${{ matrix.deps }}
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php: [ 8.2, 8.3, 8.4, 8.5 ]
                deps: [ highest ]
                symfony: [ 6.4.*, 7.3.*, 7.4.* ]
                include:
                    - php: 8.2
                      deps: lowest
                      symfony: '*'
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php }}
                  coverage: none
                  tools: flex

            - name: Install dependencies
              uses: ramsey/composer-install@v3
              with:
                  dependency-versions: ${{ matrix.deps }}
                  composer-options: --prefer-dist
              env:
                  SYMFONY_REQUIRE: ${{ matrix.symfony }}

            - name: Test
              run: vendor/bin/phpunit
